### PR TITLE
1.0.0 Branch created.

### PR DESCRIPTION
**Pull request by twcook**
This is my concept of the directory structure that should allow for continuous development of the various microservices without the need to restructure during development.

The documentation is in the docs directory in Markdown files. the gh-pages setup should render it without further build tasks. 

Please checkout branch 1.0.0 and let me know if this is useful.

### CODE REVIEW

**Comment by daveshap** [comment]
Hey Tim, definitely like the documentation! First question: I noticed that there's a separate services folder outside the release. I don't think this is the right way to go because the microservices paradigms might change from one release to the next. For instance, we might establish certain standards and defaults that make sense in R1, which we will want to preserve. But then, once we move to R2, we might establish new standards. This will give us very clean versioning as RAVEN evolves. Does that make sense? 

Also, if I'm misunderstanding the folder structure, please let me know.

**Comment by twcook** [comment]
> 
Dave,

Git branches handle the versioning process. With the folder approach you are talking about then, you cannot create "releases" of individual versions because all "R" folders will be in every released version. This would certainly cause confusion for implementers.

Maybe you are thinking about creating release versions of each individual microservice? I'm thinking that all microservices in each released version must be testable as a package. 

Anyway, this is the point where we have to decide on a release process. Typically, I have a versioned branch. Once it is fully documented and tested, it is pulled into the main branch and frozen for a release package/application. 

Your thoughts?

**Comment by daveshap** [comment]
That makes sense, Tim! It sounds like we need to do a bit more workshopping around repo organization and come to consensus with the group. I'm working on scheduling a call with Tim Foote, another leader. Would you like to participate in a Zoom/Teams call to discuss?

**Comment by timfoote** [comment]
Great work @twcook.  Looking forward to connecting soon.  Could you update the contributors section to reference the code of conduct draft [wiki page](https://github.com/daveshap/raven/wiki/Code-of-Conduct-(draft))?

**Comment by twcook** [comment]
> Great work @twcook. Looking forward to connecting soon. Could you update the contributors section to reference the code of conduct draft [wiki page](https://github.com/daveshap/raven/wiki/Code-of-Conduct-(draft))?

I like the Code of Conduct wiki page as well. However, 

> That makes sense, Tim! It sounds like we need to do a bit more workshopping around repo organization and come to consensus with the group. I'm working on scheduling a call with Tim Foote, another leader. Would you like to participate in a Zoom/Teams call to discuss?

Yes. I have a fairly wide availability profile. If there is a scheduling tool that you use, feel free to send me a link.

**Comment by twcook** [comment]
> That makes sense, Tim! It sounds like we need to do a bit more workshopping around repo organization and come to consensus with the group. I'm working on scheduling a call with Tim Foote, another leader. Would you like to participate in a Zoom/Teams call to discuss?

Yes, please.

**Pull request closed without merging**
